name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: microservicio-tareas

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar pruebas con cobertura
        run: pytest --cov=. --cov-report=term

      - name: Analisis SAST con Bandit
        run: bandit -r app.py

      - name: Analisis SCA con pip-audit
        run: pip-audit -r requirements.txt

      - name: Construir imagen Docker
        run: docker build -t microservicio-tareas .